### ISSUE TITLE
Erro Commit-stream --token xxxxxxxxxx

### ISSUE THREAD

**Issue by meetgyn** [x1sec/commit-stream#1]
I've tried anyway to put the token, however when I try to execute command with --email, it gives an error and keeps asking for the token, what should I do? 

 ./commit-stream --token xxxxxxxxxx

**Comment by x1sec** [comment]
Could you provide the complete output when you get this error (with any sensitive information masked) ?

**Comment by meetgyn** [comment]
Hello, sorry delay.
When I run a script with parameter --email '@ gmail.com', it stops and returns nothing. He stayed more than 2 hours and never returned.



Stream Github commit authors in realtime

Usage:
  commit-stream [OPTIONS]

Options:
  -e, --email        Match email addresses field (specify multiple with comma). Omit to match all.
  -n, --name         Match author name field (specify multiple with comma). Omit to match all.
  -t, --token        Github token (if not specified, will use environment variable 'CSTREAM_TOKEN')
  -a  --all-commits  Search through previous commit history (default: false)
  -i  --ignore-priv  Ignore noreply.github.com private email addresses (default: false)


**root@Lab1:/opt/osint/commit-stream# ./commit-stream --email '@totvs.com.br'**

**Comment by x1sec** [comment]
In the example you provided above, there is a space between the @ and gmail.com.
