### ISSUE TITLE
<Q> Rate Limiting Capability?

### ISSUE THREAD

**Issue by T0tal-T0sser-Account** [x1sec/commit-stream#10]
RobHax,

Thanks up front for the tool - very interesting, proactive, defensive possibilities.

Do you, or does the community, have usage suggestions to fall beneath what Github would consider 'abuse' of their API?  I had a script halted from, I presume, Github's end citing 'abuse'; it didn't lock my account, but I'd like to stay within the realm of acceptable use.  So, I'm curious if there is a rate limiting capability, a suggested 'use time' (e.g., < 30 min), or similar to eliminate 'abusive' scenarios.

Warm regards,
B

**Comment by x1sec** [comment]
commit-stream will report if the rate limit has been hit with the following message: `Hit rate limit.` 
In this situation it will pause execution. If abuse of the API is reported from Github, commit-stream will print the message `Abuse detected!` then exit.

If neither of these messages outputted (to `stderr`) then it is unlikely that the tool was behaving in an unacceptable manner.
Upto 5000 requests are permitted per hour as documented [here](https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting). `commit-stream` should not exceed this allowed quota.

Also note it is not allowed to use multiple tokens at the same time. commit-stream only requires one.

If there are any error messages when the software halted, it would be useful for you to provide them here.

**Comment by T0tal-T0sser-Account** [comment]
The script received 'Abuse detected!' and exited.  I was using a single token and running a single instantiation of commit-stream.  Do you know if Github publicly declares the 5000 requests per hour limit - I wonder if they've lowered the request limit?

Thanks for responding!

**Comment by x1sec** [comment]
The code is written to only perform one request per second which totals 3600 requests in an hour which is under 5000.
Are you running it through a virtual private server or shared IP (e.g. with a VPN)? Perhaps there is another reason why Abuse was detected. 

You can comment out this line and re-compile to have it print out what the API returns in regards to requests remaining and your request limit:

https://github.com/x1sec/commit-stream/blob/master/pkg/gitevents.go#L134

e.g.:
`4792/5000 remaining`

Either way I will do some further testing.

**Comment by T0tal-T0sser-Account** [comment]
I was most likely running it via ProtonVPN - maybe Github was basing 'abuse' off of source IP?  I'll test offline of the VPN and get back to you.

Gracias.

**Comment by x1sec** [comment]
Likely, I have been consistently running it for ~2 days without any issues. I'll wait for you response then close the issue.

**Comment by T0tal-T0sser-Account** [comment]
I've been running the script for 4 hours (offline of the VPN) with no issues - I think this is a candidate for closure.  Maybe a disclaimer. with the tool, that running through a VPN may trigger an abuse flag from Github?

Thanks so much for the help and the technical exchange - take care!
