### ISSUE TITLE
Great Tool! just had a quick question

### ISSUE THREAD

**Issue by obheda12** [x1sec/commit-stream#11]
How is the metadata extraction happening exactly? I can't seem to find the email string anywhere in the repositories that return in the results.

For example if one of the results contains john.seeru@apple.com:

I wouldn't be able necessarily to find that string anywhere in the code of he repository. Where in that case is the result being extracted from and how would i manually be able to identify it on GitHub?

**Comment by x1sec** [comment]
If you clone a repository you can see the commit logs with `git log`.
Github also exposes an [API](https://docs.github.com/en/rest/reference/repos#commits), for example:
https://api.github.com/repos/octocat/Hello-World/commits
