### ISSUE TITLE
zsh: exec format error: ./commit-stream

### ISSUE THREAD

**Issue by Hanh94** [x1sec/commit-stream#12]
I'm having a usage problem
When I downloaded commit-stream-linux-amd64.zip, the executable file failed to execute
`zsh: exec format error: /Users/hanh/Downloads/commit-stream`

 go version: `go version go1.15 darwin/amd64`

**Comment by x1sec** [comment]
Use [commit-stream-darwin-amd64](https://github.com/x1sec/commit-stream/releases/download/v0.2.0/commit-stream-darwin-amd64) release for MacOS
