### ISSUE TITLE
No handling for 502 status codes

### ISSUE THREAD

**Issue by nikitastupin** [x1sec/commit-stream#6]
After working for some time `commit-stream` exists printing this to stderr:

```
$ commit-stream -t TOKEN -i | cut -d ',' -f 2 >> all.txt
GET https://api.github.com/events?page=3&per_page=300: 502  []
```

I propose to handle 502 status code with retries and logging about 502 to stderr but not exiting program.

**Comment by x1sec** [comment]
Handling for a 502 (Bad Gateway) will output to stderr and sleep for 5 seconds before continuing execution. The 5 seconds is arbitrary as I'm not quite sure what would cause this error.

@nikitastupin if you observe many of these errors, please let me know as it may imply some other changes are needed.
