### ISSUE TITLE
Release .zip for linux

### ISSUE THREAD

**Issue by 1efty** [x1sec/commit-stream#8]
Any chance that the linux release could also be released in a zip? For the sake of cross-platform automation? Not saying remove .gz but also release as a zip.

**Comment by x1sec** [comment]
gunzip comes default in most (all?) Linux distributions, while unzip does not, hence the decision for just the .gz. Next release I will add a .zip version.

**Comment by x1sec** [comment]
Since it has been a while and a new release has yet to come, I have created a .zip version as requested in the current release:

https://github.com/x1sec/commit-stream/releases/download/v0.1.2/commit-stream-linux-amd64.zip
