### ISSUE TITLE
Error while building from source 

### ISSUE THREAD

**Issue by bugbaba** [x1sec/commit-stream#9]
Hi,

When I am trying to build the binary from the code I am getting the following error.

```
./commit-stream.go:94:100: unknown field 'Rate' in struct literal of type commitstream.StreamOptions
```

![image](https://user-images.githubusercontent.com/29960776/100085616-409b4880-2e72-11eb-9b11-05d5173d167a.png)

--
Regards,
@bugbaba

**Comment by x1sec** [comment]
I'm not too sure what would be causing this issue. If your go environment is setup correctly, try:
$ go get -u github.com/x1sec/commit-stream

**Comment by bugbaba** [comment]
The `go get ` command is working fine and the binary is getting download and working properly, But again when I try to make changes in the `commit-stream` code in `$mygopath/src/` path and rebuild the code it gives the same error.

I wanted to make few minor changes for my use case, hence wanted to build from source :)

**Comment by x1sec** [comment]
It is likely that there is an issue with the changes you made or your go environment. Was the issue solved?

**Comment by bugbaba** [comment]
No its still giving the same error and as you can see in the screenshot I am just git cloning the repository and running go build without any changes in the code. I am using the default settings provided by repl.it

**Comment by x1sec** [comment]
To clarify, are you are running it directly from the web browser with the https://repl.it/ service?

**Comment by bugbaba** [comment]
To make changes and build binary yes, But I am running the binary from my VPS.

**Comment by x1sec** [comment]
It seems repl.it is using go version 1.14.7 which is outdated.
The software builds fine on the latest release. Recommend building locally rather then on repl.it hosted service.
